//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigo { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public byte[] ultimo_acesso { get; set; }
    }
}
