//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Net.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [Display (Name = "Código")]
        public int codigo { get; set; }
        [Display (Name = "E-mail")]
        public string email { get; set; }
        [Display(Name = "Senha")]
        public string senha { get; set; }
        [Display (Name = "Último Acesso")]
        public byte[] ultimo_acesso { get; set; }
    }
}
